routes/web.php
<?php

use App\Http\Controllers\Ajax\AjaxAdressController;
use App\Http\Controllers\UploadController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('ajax/address', [AjaxAdressController::class, 'getAdressById'])->name('ajax.address');

Route::any('image/upload', [UploadController::class, 'upload'])->name('image.upload');

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Storage;

class Menu extends BaseModel
{
    protected $fillable = [
        'name',
        'slug',
        'order',
        'status',
        'parent_id',
        'type_id',
        'meta_title',
        'meta_description',
        'meta_keywords',
        'meta_thumb',
        'image',
    ];

    public $timestamps = true;

    protected $filterable = ['id', 'parent_id'];

    public function type()
    {
        return $this->belongsTo(MenuType::class, 'type_id');
    }

    public function parentMenu()
    {
        return $this->belongsTo($this, 'parent_id');
    }

    public function getThumbAttribute()
    {
        return Storage::url($this->image);
    }

    public function getMetaImageAttribute()
    {
        return Storage::url($this->meta_thumb);
    }
}

app/Models/MenuType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MenuType extends Model
{
    use HasFactory;
}

app/Http/Controllers/Backend/MenuController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\MenuRequest;
use App\Services\MenuService;
use App\Traits\UploadImage;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    use UploadImage;

    protected $menuService;

    public function __construct(MenuService $menuService)
    {
        $this->menuService = $menuService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $data = $this->menuService->listMenu($request);
        return view('backend.pages.menus.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $data = $this->menuService->createMenu();
        return view('backend.pages.menus.createOrUpdate', $data);
    }

    public function config()
    {
        return [
            'title' => 'Create or Update menu',
            'parentBreadcrumb' => "Manage menu",
            'prefix' => 'menus',
        ];
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(MenuRequest $request)
    {
        $data = $this->menuService->storeMenu($request);

        if (!$data) return $this->redirectBack('err', 'Exist slug.');
        
        return $this->redirectBack('msg', 'New menu added successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = $this->menuService->editMenu($id);
        return view('backend.pages.menus.createOrUpdate', $data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(MenuRequest $request, string $id)
    {
        $this->menuService->updateMenu($request, $id);
        return $this->redirectBack('msg', 'Menu updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $this->menuService->deleteMenu($id);
        return $this->redirectBack('msg', 'Menu deleted successfully.');
    }
}

resources/views/backend/pages/menus/inc/filter.blade.php
<div class="mb-2">
    <form action="{{ route('admin.'.$prefix.'.index') }}" method="GET">
        <fieldset class="border rounded-sm p-2 text-sm">
            <legend class="text-gray-500">Filter</legend>
            <div class="flex items-center justify-between">
                <div>
                    <select class="border rounded-sm py-1 px-2 outline-none" name="limit" id="">
                        <option value="25" selected>Options</option>
                        @foreach (options() as $option)
                            <option value="{{ $option }}" {{ request('limit') == $option ? 'selected' : '' }}>
                                {{ $option }}
                            </option>
                        @endforeach
                        <option value="all">Show all</option>
                    </select>
                </div>
                <div class="flex flex-wrap gap-2 justify-end">
                    {{-- <select class="border rounded-sm py-1 px-2 outline-none" name="status" id="">
                        <option value="" selected>--Status--</option>
                        <option value="1" {{ request('status') == "1" ? 'selected' : '' }}>Active</option>
                        <option value="0" {{ request('status') == "0" ? 'selected' : '' }}> Non-active</option>
                    </select> --}}

                    <input type="search" value="{{ request('search') ?? old('search') }}" name="search"
                        class="border rounded-sm focus:outline-0 py-1 px-4" placeholder="Search...">

                    <button type="submit"
                        class="px-5 hover:opacity-70 py-1 text-white rounded-sm bg-gray-800">Search</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>

resources/views/backend/pages/menus/inc/table.blade.php
<table class="border-collapse w-full text-sm">
    <thead>
        <th class="border bg-gray-50 uppercase p-2 text-center">
            <input type="checkbox" id="mainCheckbox">
        </th>
        <th class="border bg-gray-50 uppercase p-2 text-center">#</th>
        <th class="border bg-gray-50 uppercase p-2">Image</th>
        <th class="border bg-gray-50 uppercase p-2">Name</th>
        <th class="border bg-gray-50 uppercase p-2">Slug</th>
        <th class="border bg-gray-50 uppercase p-2">Order</th>
        <th class="border bg-gray-50 uppercase p-2">Parent</th>
        <th class="border bg-gray-50 uppercase p-2">Type</th>
        <th class="border bg-gray-50 uppercase p-2">Prefix</th>
        <th class="border bg-gray-50 uppercase p-2">Status</th>
        <th class="border bg-gray-50 uppercase p-2"></th>
    </thead>
    <tbody>
        @forelse ($data as $item)
            <tr>
                <td class="border p-2 text-center">
                    <input type="checkbox" id="checkboxItem" value="{{ $item->id }}">
                </td>
                <td class="border p-2 text-center">
                    {{ $item->id }}
                </td>
                <td class="border p-2 text-center">
                    <div class="w-12 h-12 mx-auto flex items-center justify-center p-0.5 bg-gradient-to-br from-blue-700 to-white rounded-full border">
                        @if ($item->image)
                            <img src="{{ $item->thumb }}" class="rounded-full w-full h-full" alt="">
                        @else
                            -
                        @endif
                    </div>
                </td>
                <td class="border p-2">
                    {{ $item->name }}
                </td>
                <td class="border p-2">
                    {{ $item->slug }}
                </td>
                <td class="border p-2">
                    <input type="number" name="" max="100" step="5" min="0"
                        class="orderNumber outline-none border w-full p-2 rounded-sm" value="{{ $item->order ?? 0 }}"
                        data-id="{{ $item->id }}">
                </td>
                <td class="border p-2">
                    @if ($item->parent_id > 0)
                        <a href="?id={{ $item->parent_id }}" class="text-blue-500 hover:underline">
                            {{ $item->parent_id }} - {{ $item->parentMenu->name ?? '' }}
                        </a>
                    @else
                        {{ $item->parent_id }}
                    @endif
                </td>
                <td class="border p-2 text-center">
                    {{ $item->type->name ?? '' }}
                </td>
                <td class="border p-2 text-center">
                    {{ $item->sku_prefix ?? '-'}}
                </td>
                <td class="border p-2">
                    <div class="flex flex-col items-center gap-2">
                        <label class="cursor-pointer sw-toggle">
                            <input id="toggleStatusCheckbox{{ $item->id }}" data-id="{{ $item->id }}"
                                type="checkbox" class="toggle-checkbox" data-url="{{ $toggleStatusUpdate }}"
                                value="{{ $item->status }}" {{ $item->status ? 'checked' : '' }} />
                        </label>
                    </div>
                </td>
                <td class="border p-2">
                    <div class="flex flex-wrap justify-center gap-1">
                        <a href="{{ route('admin.' . $prefix . '.edit', $item->id) }}"
                            class="bg-blue-700 rounded-sm w-8 h-7 flex items-center justify-center text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor"
                                class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path
                                    d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z" />
                            </svg>
                        </a>
                        <a href="#"
                            onclick="event.preventDefault(); return confirm('Are you sure to delete item {{ $item->name }}?') ? document.getElementById('deleteForm{{ $item->id }}').submit() : false"
                            class="bg-red-500 rounded-sm w-8 h-7 flex items-center justify-center text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor"
                                class="bi bi-trash2-fill" viewBox="0 0 16 16">
                                <path
                                    d="M2.037 3.225A.7.7 0 0 1 2 3c0-1.105 2.686-2 6-2s6 .895 6 2a.7.7 0 0 1-.037.225l-1.684 10.104A2 2 0 0 1 10.305 15H5.694a2 2 0 0 1-1.973-1.671zm9.89-.69C10.966 2.214 9.578 2 8 2c-1.58 0-2.968.215-3.926.534-.477.16-.795.327-.975.466.18.14.498.307.975.466C5.032 3.786 6.42 4 8 4s2.967-.215 3.926-.534c.477-.16.795-.327.975-.466-.18-.14-.498-.307-.975-.466z" />
                            </svg>
                        </a>

                        <button
                            class="bg-blue-400 rounded-sm w-8 h-7 flex items-center justify-center text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
                                <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
                              </svg>
                        </button>

                        <form id="deleteForm{{ $item->id }}" class="hidden"
                            action="{{ route('admin.' . $prefix . '.destroy', $item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                        </form>
                    </div>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="20" class="p-3 border">[Empty item]</td>
            </tr>
        @endforelse
    </tbody>
    @if ($data->count())
        <tfoot>
            <tr>
                <td colspan="20" class="border p-2">
                    <div>{{ $data->links('pagination::tailwind') }}</div>
                </td>
            </tr>
        </tfoot>
    @endif
</table>